version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "/home/admin/jenkins_home:/var/jenkins_home"
    networks:
      - net
  sshtesting:
    container_name: sshcreation
    image: sshtestin
    build: 
      context: Debian
    networks:
      - net
networks:
  net:
